services:
  db:
    image: postgres:16.3
    container_name: postgres
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=nest_rest
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    restart: always
    build:
      dockerfile: Dockerfile.dev
    container_name: backend
    volumes:
      - ./:/usr/src/app/
    ports:
      - '80:3000'
    depends_on:
      - db
    env_file:
      - ./.env.dev
    command: pnpm run start:dev

volumes:
  postgres-data:
